IGNORE_INDEX = -100

DEFAULT_IMAGE_TOKEN = "<image>"
DEFAULT_VIDEO_TOKEN = "<video>"
DEFAULT_TRAJ_TOKEN = "<traj>"
DEFAULT_STOP_TOKEN = "<stop>"


IMAGE_TOKEN_ID = 151655
VIDEO_TOKEN_ID = 151656
VISION_START_TOKEN_ID = 151652
